/**
 * Official Development Fixture for Stage 2 — Review Center.
 * Based directly on hackathon Study Sentinel worked examples (042-S02-004, 042-S07-001, 042-S11-005).
 * Kept isolated in this file so the UI can seamlessly point to real backend endpoints later.
 */

import { ReviewCenterData, ReviewCase } from '../lib/reviewApi';

export const officialCase017: ReviewCase = {
  id: 'case-017',
  caseNumber: 'CASE 017',
  usubjid: '042-S02-004',
  siteId: 'S02',
  title: 'Serious adverse event coding conflict',
  category: 'safety',
  stage: 'human_gate',
  decisionStatus: 'AWAITING',
  priority: 'high',
  cut: 12,
  openDuration: '2 hours ago',
  evidenceCount: 1,
  whatHappened: {
    summary: 'Cellulitis was recorded as not serious, but the subject was hospitalised.',
    facts: [
      { label: 'Reported Term', value: 'Cellulitis' },
      { label: 'Hospitalised (AESHOSP)', value: 'YES', highlight: true },
      { label: 'Entered Serious (AESER)', value: 'NO', highlight: true },
      { label: 'Severity', value: 'SEVERE' },
    ],
    protocolRule: 'Protocol §6: Hospitalisation makes the event serious regardless of the investigator entered AESER flag.',
  },
  whyItMatters:
    'This may require expedited safety reporting because the study protocol treats hospitalisation as a serious adverse event regardless of the entered AESER flag.',
  journey: [
    {
      stageName: 'DETECTED',
      time: '09:41',
      title: 'Atlas detected discrepancy',
      description: 'Atlas noticed a conflict between AESER and AESHOSP in safety surveillance.',
      evidence: 'AE · Sequence 1',
      status: 'completed',
    },
    {
      stageName: 'MEDICAL REVIEW',
      time: '09:41',
      title: 'Safety criteria satisfied',
      description: 'Serious event criteria satisfied based on inpatient admission.',
      recommendation: 'Escalate to medical monitor.',
      status: 'completed',
    },
    {
      stageName: 'COMPLIANCE',
      time: '09:42',
      title: 'Protocol verification',
      description: 'Protocol §6 (SAE expedited definitions) confirmed applicability.',
      status: 'completed',
    },
    {
      stageName: 'HUMAN GATE',
      time: 'NOW',
      title: 'Medical monitor decision required',
      description: 'Pending clinician adjudication on safety escalation and report generation.',
      status: 'current',
    },
    {
      stageName: 'ACTION',
      time: 'Pending',
      title: 'Action execution',
      description: 'Awaiting human authorization to initiate expedited regulatory reporting.',
      status: 'pending',
    },
  ],
  humanGate: {
    requiredDecision: 'What should happen next?',
    monitorQuestion: 'Confirm whether cellulitis meets serious adverse event criteria for expedited safety filing.',
    executedAction: 'Expedited serious-event report initiated to sponsor safety and regulatory board within 24 hours.',
    decisionReason: 'Hospitalisation overrides local AESER flag per protocol §6 safety criteria.',
  },
  rawTrace: [
    { timestamp: '09:41:02', stage: 'detect', action: 'Finding created', detail: 'SAE_MISCODED flagged for 042-S02-004', evidenceRef: 'AE:1' },
    { timestamp: '09:41:03', stage: 'medical_review', action: 'Escalation recommended', detail: 'AESHOSP=Y overrides AESER=N per protocol §6' },
    { timestamp: '09:41:03', stage: 'compliance', action: 'Rule matched', detail: 'ICH E2A expedited reporting clock started' },
    { timestamp: '09:41:04', stage: 'human_gate', action: 'Awaiting human', detail: 'Queued to medical monitor inbox' },
  ],
};

export const officialCase042: ReviewCase = {
  id: 'case-042',
  caseNumber: 'CASE 042',
  usubjid: '042-S07-001',
  siteId: 'S07',
  title: 'Potential Hy’s Law liver safety elevation',
  category: 'safety',
  stage: 'human_gate',
  decisionStatus: 'AWAITING',
  priority: 'high',
  cut: 12,
  openDuration: '4 hours ago',
  evidenceCount: 2,
  whatHappened: {
    summary: 'Biochemical criteria for potential Hy’s Law met at Week 8 visit with marked ALT elevation.',
    facts: [
      { label: 'ALT Level', value: '3.995 µkat/L (4.30x ULN)', highlight: true },
      { label: 'Total Bilirubin', value: '5.38 µmol/L (2.1x ULN)', highlight: true },
      { label: 'Visit', value: 'WEEK 8' },
      { label: 'Status', value: 'UNCONFIRMED_ADJUDICATION_REQUIRED' },
    ],
    protocolRule: 'Protocol §7.2: ALT/AST > 3x ULN accompanied by Total Bilirubin > 2x ULN mandates immediate monitor adjudication.',
  },
  whyItMatters:
    'Severe drug-induced liver injury (DILI) risk. Requires verification of baseline values and concomitant hepatotoxins prior to safety reporting or drug pause.',
  journey: [
    {
      stageName: 'DETECTED',
      time: '08:15',
      title: 'Biochemical criteria flagged',
      description: 'Atlas detected concurrent ALT > 3x ULN and BILI > 2x ULN at Cut 12 snapshot.',
      evidence: 'LB · Sequence 25, 27',
      status: 'completed',
    },
    {
      stageName: 'MEDICAL REVIEW',
      time: '08:17',
      title: 'Potential Hy’s Law review',
      description: 'Evaluated transaminases and bilirubin time-window overlap.',
      recommendation: 'Request clarification on screening baseline and concomitant medications.',
      status: 'completed',
    },
    {
      stageName: 'COMPLIANCE',
      time: '08:18',
      title: 'Protocol §7 validation',
      description: 'Adjudication protocol checklist generated.',
      status: 'completed',
    },
    {
      stageName: 'HUMAN GATE',
      time: 'NOW',
      title: 'Medical monitor clarification needed',
      description: 'Monitor requires baseline and medication context.',
      status: 'current',
    },
    {
      stageName: 'ACTION',
      time: 'Pending',
      title: 'Clinical safety disposition',
      description: 'Pending resolution of clarification inquiry.',
      status: 'pending',
    },
  ],
  humanGate: {
    requiredDecision: 'What should happen next?',
    monitorQuestion: 'What was this subject’s screening ALT, and are they receiving any other liver-affecting medication?',
    clarifyTarget: {
      testCode: 'ALT',
      visit: 'SCREENING',
      expectedValue: '0.27 µkat/L (0.29x ULN)',
      concomitantCheck: 'Checked 3 concomitant medications in CM: No hepatotoxic medications recorded.',
    },
    executedAction: 'Expedited safety review completed. Drug-042 continued under enhanced 48-hour liver monitoring.',
    decisionReason: 'Baseline was normal; acute spike at Week 8 followed by spontaneous resolution to 0.33 µkat/L at EOS.',
  },
  rawTrace: [
    { timestamp: '08:15:20', stage: 'detect', action: 'Flagged', detail: 'POTENTIAL_HYS_LAW triggered on LB:25 (ALT) and LB:27 (BILI)' },
    { timestamp: '08:17:11', stage: 'medical_review', action: 'Evaluate', detail: 'Criteria satisfied; query monitor for baseline history' },
    { timestamp: '08:18:04', stage: 'human_gate', action: 'Question posed', detail: 'Sent to monitor: Check screening transaminases' },
  ],
};

export const officialCase088: ReviewCase = {
  id: 'case-088',
  caseNumber: 'CASE 088',
  usubjid: '042-S11-005',
  siteId: 'S11',
  title: 'Adverse event onset precedes first study dose',
  category: 'data_quality',
  stage: 'data_compliance',
  decisionStatus: 'AWAITING',
  priority: 'medium',
  cut: 12,
  openDuration: '1 day ago',
  evidenceCount: 2,
  whatHappened: {
    summary: 'AE start date was recorded as prior to the first dose of investigational product.',
    facts: [
      { label: 'AE Start Date (AESTDTC)', value: '2026-01-10', highlight: true },
      { label: 'First Dose Date (EXSTDTC)', value: '2026-01-15', highlight: true },
      { label: 'Domain', value: 'AE vs EX' },
      { label: 'Current State', value: 'Waiting for site response' },
    ],
    protocolRule: 'Data Standard §4.1: Pre-treatment medical occurrences must be recorded in Medical History (MH), not Adverse Events (AE).',
  },
  whyItMatters:
    'Conflating baseline pre-existing conditions with treatment-emergent adverse events skews safety incidence statistics for Drug-042.',
  journey: [
    {
      stageName: 'DETECTED',
      time: 'Yesterday',
      title: 'Chronology conflict detected',
      description: 'Automated temporal cross-check identified AESTDTC prior to EXSTDTC.',
      evidence: 'AE:1 · EX:1',
      status: 'completed',
    },
    {
      stageName: 'DATA / COMPLIANCE',
      time: 'Yesterday',
      title: 'Site query generated',
      description: 'Formal eCRF query dispatched to Site S11 principal investigator.',
      recommendation: 'Awaiting site response: verify whether date typo or medical history entry.',
      status: 'current',
    },
    {
      stageName: 'HUMAN GATE',
      time: 'Queued',
      title: 'Data manager sign-off',
      description: 'Will review site amendment once query response is received.',
      status: 'pending',
    },
    {
      stageName: 'ACTION',
      time: 'Pending',
      title: 'Database lock reconciliation',
      description: 'Pending correction in electronic data capture.',
      status: 'pending',
    },
  ],
  rawTrace: [
    { timestamp: '14:22:00', stage: 'detect', action: 'Temporal conflict', detail: 'AESTDTC 2026-01-10 < EXSTDTC 2026-01-15' },
    { timestamp: '14:22:15', stage: 'data_compliance', action: 'Site query dispatched', detail: 'Query #S11-Q08 dispatched to EDC' },
  ],
};

export const officialCase029: ReviewCase = {
  id: 'case-029',
  caseNumber: 'CASE 029',
  usubjid: '042-S01-007',
  siteId: 'S01',
  title: 'Severe anaphylaxis SAE expedited reporting',
  category: 'safety',
  stage: 'action_monitoring',
  decisionStatus: 'APPROVED',
  priority: 'high',
  cut: 12,
  openDuration: '3 days ago',
  evidenceCount: 1,
  whatHappened: {
    summary: 'Acute anaphylactoid reaction within 45 minutes of dose 1; hospitalization required.',
    facts: [
      { label: 'Event', value: 'Anaphylactic Reaction' },
      { label: 'Severity', value: 'GRADE 3' },
      { label: 'Hospitalized', value: 'YES' },
      { label: 'De-challenge', value: 'Drug Discontinued' },
    ],
    protocolRule: 'Protocol §6.1: Immediate expedited 24-hour reporting for life-threatening or disabling hypersensitivity events.',
  },
  whyItMatters: 'Suspected unexpected serious adverse reaction (SUSAR) requiring institutional review board and regulatory agency notification.',
  journey: [
    { stageName: 'DETECTED', time: '3d ago', title: 'SAE logged', description: 'AESER=Y and AESHOSP=Y verified.', status: 'completed' },
    { stageName: 'MEDICAL REVIEW', time: '3d ago', title: 'Urgent escalation', description: 'Approved for regulatory reporting.', status: 'completed' },
    { stageName: 'HUMAN GATE', time: '3d ago', title: 'Medical monitor sign-off', description: 'Immediate electronic approval granted.', status: 'completed' },
    { stageName: 'ACTION / MONITORING', time: 'Active', title: 'Regulatory dossier filed', description: 'Expedited MedWatch/CIOMS submitted; safety monitoring ongoing.', status: 'current' },
    { stageName: 'RESOLVED', time: 'Pending', title: 'Resolution pending follow-up', description: 'Follow-up safety telemetry due Week 4.', status: 'pending' },
  ],
  rawTrace: [
    { timestamp: '10:02:11', stage: 'detect', action: 'SAE detected', detail: 'Grade 3 Anaphylaxis in S01-007' },
    { timestamp: '10:05:00', stage: 'human_gate', action: 'Approved by Monitor', detail: 'Dr. E. Vance approved 24h filing' },
  ],
};

export const officialCase104: ReviewCase = {
  id: 'case-104',
  caseNumber: 'CASE 104',
  usubjid: '042-S05-003',
  siteId: 'S05',
  title: 'Prohibited sulfonylurea (Glimepiride) concomitant intake',
  category: 'compliance',
  stage: 'resolved',
  decisionStatus: 'APPROVED',
  priority: 'medium',
  cut: 12,
  openDuration: '5 days ago',
  evidenceCount: 1,
  whatHappened: {
    summary: 'Subject was prescribed Glimepiride by primary care physician, which is strictly prohibited under Protocol v3.',
    facts: [
      { label: 'Medication', value: 'Glimepiride (4mg daily)' },
      { label: 'Class', value: 'SULFONYLUREA' },
      { label: 'Protocol Amendment', value: 'Protocol v3 §5.4' },
      { label: 'Resolution', value: 'Medication discontinued; switched to approved metformin' },
    ],
    protocolRule: 'Protocol v3 §5.4: Sulfonylureas are prohibited due to interference with primary glycemic endpoint assessment.',
  },
  whyItMatters: 'Concomitant sulfonylureas confound HbA1c trajectory and may obscure efficacy comparisons against placebo.',
  journey: [
    { stageName: 'DETECTED', time: '5d ago', title: 'CM coded sulfonylurea', description: 'Automated CMCLAS scan flagged Glimepiride.', status: 'completed' },
    { stageName: 'DATA / COMPLIANCE', time: '5d ago', title: 'Protocol deviation notice', description: 'Issued protocol compliance alert to Site S05.', status: 'completed' },
    { stageName: 'HUMAN GATE', time: '4d ago', title: 'Study coordinator action', description: 'Investigator confirmed medication replaced; patient retained.', status: 'completed' },
    { stageName: 'RESOLVED', time: '2d ago', title: 'Case resolved', description: 'Patient safely transitioned; deviation closed with note to file.', status: 'completed' },
  ],
  rawTrace: [
    { timestamp: '11:14:02', stage: 'detect', action: 'Prohibited med', detail: 'Glimepiride CM:3 violates v3 §5.4' },
    { timestamp: '16:30:19', stage: 'resolved', action: 'Closed', detail: 'Investigator note to file verified' },
  ],
};

export const officialCase063: ReviewCase = {
  id: 'case-063',
  caseNumber: 'CASE 063',
  usubjid: 'Site S04 Cohort',
  siteId: 'S04',
  title: 'Recurring visit-window deviations (> ±3 days)',
  category: 'site_pattern',
  stage: 'action_monitoring',
  decisionStatus: 'APPROVED',
  priority: 'high',
  cut: 12,
  openDuration: '2 days ago',
  evidenceCount: 6,
  whatHappened: {
    summary: 'Site S04 accumulated 8 visit window deviations in Cut 12 following Protocol v3 tightening of visit windows from ±7 days to ±3 days.',
    facts: [
      { label: 'Site', value: 'Site S04' },
      { label: 'Deviations', value: '8 visits outside ±3 day window' },
      { label: 'Root Cause', value: 'Coordinator scheduling using old v1 calendar template' },
      { label: 'Corrective Action', value: 'Re-training and calendar template updated' },
    ],
    protocolRule: 'Protocol v3 §3.2: Visit windows tightened to ±3 days to ensure pharmacodynamic blood sampling integrity.',
  },
  whyItMatters: 'Systematic visit delays impair per-protocol dataset integrity and introduce time-varying bias into statistical models.',
  journey: [
    { stageName: 'DETECTED', time: '3d ago', title: 'Site pattern detected', description: 'Atlas detected clustering of visit window deviations at Site S04.', status: 'completed' },
    { stageName: 'MEDICAL REVIEW', time: '2d ago', title: 'Review completed', description: 'Evaluated impact on pharmacokinetic window validity.', status: 'completed' },
    { stageName: 'ACTION / MONITORING', time: 'Active', title: 'CAPA initiated', description: 'Site coordinator re-trained; surveillance active.', status: 'current' },
  ],
  rawTrace: [
    { timestamp: '13:02:11', stage: 'detect', action: 'Pattern flagged', detail: 'Cluster of 8 visit deviations at Site S04' },
    { timestamp: '14:20:00', stage: 'action', action: 'CAPA issued', detail: 'Site corrective action plan logged' },
  ],
};

export const devReviewCenterData: ReviewCenterData = {
  cut: 12,
  protocolVersion: 3,
  awaitingHumanCount: 3,
  stages: [
    { id: 'detected', label: 'Detected', count: 202, sublabel: 'Surveillance intake', color: '#38bdf8', strokeColor: '#0284c7' },
    { id: 'medical_review', label: 'Medical Review', count: 64, sublabel: 'Clinical triage', color: '#818cf8', strokeColor: '#4f46e5' },
    { id: 'data_compliance', label: 'Data / Compliance', count: 86, sublabel: 'Rule validation', color: '#06b6d4', strokeColor: '#0891b2' },
    { id: 'human_gate', label: 'Human Gate', count: 3, sublabel: 'Awaiting decision', color: '#f59e0b', strokeColor: '#d97706' },
    { id: 'action_monitoring', label: 'Action / Monitoring', count: 18, sublabel: 'In-flight execution', color: '#64748b', strokeColor: '#475569' },
    { id: 'resolved', label: 'Resolved', count: 31, sublabel: 'Completed & audited', color: '#10b981', strokeColor: '#059669' },
  ],
  cases: [officialCase017, officialCase042, officialCase088, officialCase029, officialCase104, officialCase063],
  needsAttention: [officialCase017, officialCase042, officialCase088, officialCase063],
  findingMix: [
    { category: 'safety', label: 'Safety', count: 76, percentage: 38, color: '#f87171' },
    { category: 'data_quality', label: 'Data Quality', count: 57, percentage: 28, color: '#38bdf8' },
    { category: 'compliance', label: 'Compliance', count: 49, percentage: 24, color: '#818cf8' },
    { category: 'site_pattern', label: 'Site Pattern', count: 20, percentage: 10, color: '#fbbf24' },
  ],
  outcomes: {
    approved: 142,
    clarify: 24,
    rejected: 12,
    monitoring: 24,
    total: 202,
  },
  trend: [
    { cut: 1, cutLabel: 'Cut 1', newCases: 14, resolvedCases: 4, openCases: 10 },
    { cut: 2, cutLabel: 'Cut 2', newCases: 18, resolvedCases: 8, openCases: 20 },
    { cut: 3, cutLabel: 'Cut 3', newCases: 22, resolvedCases: 12, openCases: 30 },
    { cut: 4, cutLabel: 'Cut 4', newCases: 24, resolvedCases: 16, openCases: 38 },
    { cut: 5, cutLabel: 'Cut 5', newCases: 29, resolvedCases: 20, openCases: 47 },
    { cut: 6, cutLabel: 'Cut 6', newCases: 35, resolvedCases: 24, openCases: 58 },
    { cut: 7, cutLabel: 'Cut 7', newCases: 26, resolvedCases: 28, openCases: 56 },
    { cut: 8, cutLabel: 'Cut 8', newCases: 20, resolvedCases: 25, openCases: 51 },
    { cut: 9, cutLabel: 'Cut 9', newCases: 28, resolvedCases: 27, openCases: 52 },
    { cut: 10, cutLabel: 'Cut 10', newCases: 19, resolvedCases: 26, openCases: 45 },
    { cut: 11, cutLabel: 'Cut 11', newCases: 15, resolvedCases: 22, openCases: 38 },
    { cut: 12, cutLabel: 'Cut 12', newCases: 12, resolvedCases: 25, openCases: 25 },
  ],
  sites: [
    { siteId: 'S01', name: 'Metro Health Academic', openCases: 3, openQueries: 0, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: 'All safety and timeline milestones compliant.' },
    { siteId: 'S02', name: 'University Clinical Center', openCases: 5, openQueries: 1, unansweredQueries: 0, recurringIssues: 1, status: 'watch', statusReason: '1 serious event coding discrepancy under human review.' },
    { siteId: 'S03', name: 'Valley Medical Institute', openCases: 2, openQueries: 0, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: 'Zero pending queries; routine follow-up.' },
    { siteId: 'S04', name: 'Pacific Health Network', openCases: 8, openQueries: 3, unansweredQueries: 1, recurringIssues: 2, status: 'attention', statusReason: 'Recurring visit-window deviations post Protocol v3 update.' },
    { siteId: 'S05', name: 'Highland Diabetes Center', openCases: 6, openQueries: 2, unansweredQueries: 0, recurringIssues: 1, status: 'watch', statusReason: 'Prohibited medication resolution confirmed; telemetry ongoing.' },
    { siteId: 'S06', name: 'Summit Research Hospital', openCases: 3, openQueries: 1, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: '1 query answered; source data verified.' },
    { siteId: 'S07', name: 'Memorial Clinical Trials', openCases: 9, openQueries: 2, unansweredQueries: 1, recurringIssues: 2, status: 'attention', statusReason: 'Hy’s Law candidate 042-S07-001 awaiting monitor adjudication.' },
    { siteId: 'S08', name: 'St. Jude Clinical Care', openCases: 4, openQueries: 1, unansweredQueries: 0, recurringIssues: 1, status: 'watch', statusReason: 'Creatinine exclusion re-check completed; stable.' },
    { siteId: 'S09', name: 'Lakeside Research Clinic', openCases: 2, openQueries: 0, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: 'No outstanding queries or escalations.' },
    { siteId: 'S10', name: 'Harbor City Endocrine', openCases: 3, openQueries: 1, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: 'Routine laboratory follow-up.' },
    { siteId: 'S11', name: 'Desert Ridge Medical', openCases: 7, openQueries: 3, unansweredQueries: 2, recurringIssues: 2, status: 'attention', statusReason: '2 unanswered queries regarding AE chronology errors.' },
    { siteId: 'S12', name: 'Bay Area Clinical Science', openCases: 2, openQueries: 0, unansweredQueries: 0, recurringIssues: 0, status: 'stable', statusReason: 'Excellent compliance record.' },
  ],
  memory: {
    duplicatesPrevented: 17,
    previouslyReviewed: 42,
    rejectedToMonitoring: 3,
    openSiteQueries: 8,
    recurringSubjects: 2,
    sitesUnderWatch: 1,
    summarySentence: 'The review crew remembers previous decisions so the same issue is not raised twice.',
  },
  funnel: [
    { stage: 'detected', label: 'Detected Findings', count: 202, sub: 'Surveillance intake', pct: 100 },
    { stage: 'medical_review', label: 'Medically Relevant', count: 64, sub: 'Safety & criteria verified', pct: 31.7 },
    { stage: 'action_monitoring', label: 'Action / Monitoring', count: 18, sub: 'Queries & auto-monitored', pct: 8.9 },
    { stage: 'human_gate', label: 'Human Gate Escalations', count: 3, sub: 'Medical Monitor review', pct: 1.5 },
  ],
  integrity: {
    clinicalRules: {
      hospitalizationOverrideActive: true,
      currentProtocolApplied: 'Protocol v3',
      ruleDetail: 'AESHOSP=Y treated as serious regardless of AESER flag; Protocol compliance applied dynamically.',
    },
    humanOversight: {
      clarifyResubmits: true,
      rejectedRemainMonitoring: true,
      oversightDetail: 'Monitor clarification requests answered from StudyGraph baseline and resubmitted; rejected cases retained in monitoring.',
    },
    memory: {
      duplicateQueriesBlocked: true,
      previousDecisionsRemembered: true,
      duplicateQueriesPrevented: 17,
      duplicateEscalationsPrevented: 3,
      previousDecisionsLoaded: 42,
      memoryDetail: 'System memory suppresses repeated site queries and auto-re-escalation across review cuts.',
    },
    precisionAndTrace: {
      selectiveEscalation: true,
      liveDecisionTrace: true,
      funnelRatio: '3 escalated / 202 detected (1.5%)',
      precisionDetail: 'Selective escalation ensures only qualified cases reach clinician; trace entries emitted at decision time.',
    },
  },
  whatChanged: {
    sinceCut: 11,
    currentCut: 12,
    newCases: 4,
    resolvedCases: 7,
    statusChanges: 3,
    siteNewlyFlagged: 1,
    duplicateActionsRepeated: 0,
    waterfall: {
      previousOpen: 165,
      newCount: 4,
      resolvedCount: 7,
      currentOpen: 162,
    },
    protocolImpact: {
      active: true,
      fromVersion: 2,
      toVersion: 3,
      subjectsReevaluated: 23,
      newComplianceFindings: 4,
      resolvedRules: 'Visit window narrowed ±3d; sulfonylurea prohibited.',
    },
    newCaseItems: [
      { caseNumber: 'CASE-104', usubjid: '042-S05-003', title: 'Prohibited Glimepiride therapy flagged post-v3 amendment', type: 'compliance' },
      { caseNumber: 'CASE-088', usubjid: '042-S11-005', title: 'AE date precedes first dose date', type: 'data_quality' },
      { caseNumber: 'CASE-042', usubjid: '042-S07-001', title: 'Potential Hy’s Law liver safety elevation', type: 'safety' },
      { caseNumber: 'CASE-063', usubjid: 'Site S04 Cohort', title: 'Cluster of 8 visit-window deviations post-v3 tightening', type: 'site_pattern' },
    ],
    changedCaseItems: [
      { caseNumber: 'CASE-017', usubjid: '042-S02-004', change: 'Medical Review → Human Gate (Awaiting Decision)' },
      { caseNumber: 'CASE-042', usubjid: '042-S07-001', change: 'Medical Review → Clarification (Patient 360 lookup)' },
      { caseNumber: 'CASE-029', usubjid: '042-S01-007', change: 'Human Gate → Action Executed (Expedited Report Filed)' },
    ],
    resolvedCaseItems: [
      { caseNumber: 'CASE-009', usubjid: '042-S03-002', resolution: 'Site confirmed lab unit conversion; query closed.' },
      { caseNumber: 'CASE-012', usubjid: '042-S06-004', resolution: 'AE resolution date corrected by investigator.' },
      { caseNumber: 'CASE-015', usubjid: '042-S09-001', resolution: 'Concomitant medication discontinued per protocol.' },
    ],
  },
  protocolUpdate: {
    activeVersion: 3,
    previousVersion: 2,
    subjectsReevaluated: 23,
    newFindingsIdentified: 4,
    beforeRule: 'Protocol v2: Visit window ±7 days; sulfonylureas permitted.',
    afterRule: 'Protocol v3: Visit window tightened to ±3 days; sulfonylureas strictly prohibited.',
    changedCases: [
      { subject: '042-S05-003', site: 'S05', change: 'Glimepiride newly prohibited under v3 §5.4' },
      { subject: '042-S04-002', site: 'S04', change: 'Visit 8 deviation (+5 days) non-compliant under v3' },
      { subject: '042-S04-008', site: 'S04', change: 'Visit 12 deviation (+6 days) non-compliant under v3' },
      { subject: '042-S07-009', site: 'S07', change: 'Visit 4 deviation (-4 days) newly flagged under v3' },
    ],
  },
};

